title: >-
  CriticalMAAS Milestone 2 report – Macrostrat TA4 team
author: Daven Quinn and the UW–Madison / Macrostrat CriticalMAAS team
affiliation: University of Wisconsin, Madison
date: December 20, 2023
fontsize: 11pt
geometry: margin=1in
papersize: letter
mainfont: Chaparral Pro
sansfont: Gotham Medium
numbersections: true
secnumdepth: 2
toc-depth: 2
toc: true
